// Code generated by ai/projects/topru-ai/testgen/generate_topru_cases.py. DO NOT EDIT.

package reporter

import "testing"

func TestTopRU_Gen_G2_rurecords_positive(t *testing.T) {
	runTopRUCase(t, caseSpec{
		GoalID:             "G2_rurecords_positive",
		Level:              "must",
		Description:        "payload contains RURecords with exec_count>=1 and total_ru>0",
		RequireSend:        false,
		RURecordsMin:       1,
		ExecCountMin:       1,
		ExecCountSumMin:    0,
		TotalRUMin:         1e-06,
		SQLMetaMatchMarker: "",
		PlanMetaRequired:   nil,
	})
}

func TestTopRU_Gen_G3_sqlmeta_present(t *testing.T) {
	runTopRUCase(t, caseSpec{
		GoalID:             "G3_sqlmeta_present",
		Level:              "should",
		Description:        "payload includes SQLMetas for the triggered digest/comment marker",
		RequireSend:        false,
		RURecordsMin:       0,
		ExecCountMin:       0,
		ExecCountSumMin:    0,
		TotalRUMin:         0.0,
		SQLMetaMatchMarker: "topru_gen_sqlmeta",
		PlanMetaRequired:   nil,
	})
}

func TestTopRU_Gen_G4_planmeta_present(t *testing.T) {
	runTopRUCase(t, caseSpec{
		GoalID:             "G4_planmeta_present",
		Level:              "should",
		Description:        "payload includes PlanMetas for the triggered plan digest",
		RequireSend:        false,
		RURecordsMin:       0,
		ExecCountMin:       0,
		ExecCountSumMin:    0,
		TotalRUMin:         0.0,
		SQLMetaMatchMarker: "",
		PlanMetaRequired:   boolPtr(true),
	})
}

func TestTopRU_Gen_G5_multi_records_batch(t *testing.T) {
	runTopRUCase(t, caseSpec{
		GoalID:             "G5_multi_records_batch",
		Level:              "should",
		Description:        "payload may batch multiple RURecords and must preserve counts",
		RequireSend:        false,
		RURecordsMin:       2,
		ExecCountMin:       0,
		ExecCountSumMin:    2,
		TotalRUMin:         0.0,
		SQLMetaMatchMarker: "",
		PlanMetaRequired:   nil,
	})
}

func TestTopRU_Gen_G6_total_ru_threshold(t *testing.T) {
	runTopRUCase(t, caseSpec{
		GoalID:             "G6_total_ru_threshold",
		Level:              "should",
		Description:        "payload contains a record with RU above a configured threshold",
		RequireSend:        false,
		RURecordsMin:       0,
		ExecCountMin:       0,
		ExecCountSumMin:    0,
		TotalRUMin:         1.5,
		SQLMetaMatchMarker: "",
		PlanMetaRequired:   nil,
	})
}
